//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnomalyOutput
    {
        public string PowerScout { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<double> Visibility { get; set; }
        public string days { get; set; }
        public Nullable<double> kW_System { get; set; }
        public Nullable<double> ScoredLabels { get; set; }
        public Nullable<double> ScoredProbabilities { get; set; }
        public int Id { get; set; }
        public string Breaker_details { get; set; }
    }
}
