//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassroomDetails
    {
        public int Id { get; set; }
        public string Class_Id { get; set; }
        public string Class_Description { get; set; }
        public string Building { get; set; }
        public string Breaker_details { get; set; }
        public Nullable<int> Sensor_Id { get; set; }
    }
}
