//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> AnswerID { get; set; }
        public string FeedbackDesc { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModiifiedOn { get; set; }
    
        public virtual Answers Answers { get; set; }
        public virtual ClassroomDetails ClassroomDetails { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
