//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterDetails
    {
        public int Id { get; set; }
        public string PowerScout { get; set; }
        public string Breaker_details { get; set; }
        public string PiServerName { get; set; }
        public Nullable<int> BuildingId { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
