//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyConsumptionDetails
    {
        public int Id { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Powerscout { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public string Ligne { get; set; }
        public Nullable<double> Monthly_KWH_Consumption { get; set; }
        public Nullable<double> Monthly_Electric_Cost { get; set; }
    }
}
