//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyConsumptionAzureDetails
    {
        public int Id { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string PowerScout { get; set; }
        public string Breaker_details { get; set; }
        public Nullable<double> Monthly_KWH_System { get; set; }
        public Nullable<double> Monthly_electric_cost { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<System.DateTime> current_month { get; set; }
        public Nullable<System.DateTime> last_month { get; set; }
        public string Building { get; set; }
        public string PiServerName { get; set; }
    }
}
