//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PowerGridEntities : DbContext
    {
        public PowerGridEntities()
            : base("name=PowerGridEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlertRules> AlertRules { get; set; }
        public virtual DbSet<Alerts> Alerts { get; set; }
        public virtual DbSet<AnomalyOutput> AnomalyOutput { get; set; }
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<ApplicationConfiguration> ApplicationConfiguration { get; set; }
        public virtual DbSet<ApplicationConfigurationEntry> ApplicationConfigurationEntry { get; set; }
        public virtual DbSet<Building> Building { get; set; }
        public virtual DbSet<ClassroomDetails> ClassroomDetails { get; set; }
        public virtual DbSet<DailyConsumptionDetails> DailyConsumptionDetails { get; set; }
        public virtual DbSet<DailyConsumptionPrediction> DailyConsumptionPrediction { get; set; }
        public virtual DbSet<DimDate> DimDate { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<LiveData> LiveData { get; set; }
        public virtual DbSet<MeterDetails> MeterDetails { get; set; }
        public virtual DbSet<MonthlyConsumptionDetails> MonthlyConsumptionDetails { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<PiServer> PiServer { get; set; }
        public virtual DbSet<Premise> Premise { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SensorData> SensorData { get; set; }
        public virtual DbSet<SensorLiveData> SensorLiveData { get; set; }
        public virtual DbSet<SensorMaster> SensorMaster { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WeeklyConsumptionPrediction> WeeklyConsumptionPrediction { get; set; }
    }
}
