//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorLiveData
    {
        public int Sensor_Log_Id { get; set; }
        public Nullable<int> Sensor_Id { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> Brightness { get; set; }
        public Nullable<double> Humidity { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string PiServerName { get; set; }
    }
}
